### PR TITLE
Improve showcase.md

### PR DESCRIPTION
**Pull request by LuckyPigeon**
## Description

refer to #86 

Update [showcase.md](https://github.com/pmndrs/jotai/blob/master/docs/showcase.md)

* Change `Minimal example` -> `Text Length example`
* Update `codesandbox` link
* Add description for each example

### CODE REVIEW

**Comment by LuckyPigeon** [comment]
@dai-shi 
How can we add each section of this to `README.md` of examples?

**Review by dai-shi — APPROVED** [review]
Looks good.

**Comment by dai-shi** [comment]
> How can we add each section of this to README.md of examples?

What do you mean? You just edit examples/*/README.md files?

**Comment by LuckyPigeon** [comment]
@dai-shi 
I see. I'll will start with making change on examples/*/README.md files in next change.

**Pull request merged**
