### PR TITLE
chore(build): simplify exports and support nested subpath

### PR DESCRIPTION
**Pull request by dai-shi**
- simplifies exports in package.json
- supports nested subpath in rollup.config.js
- update node version from 12 to 14

### CODE REVIEW

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/pull/697#discussion_r706712387
@Thisen Sorry, `replaceAll` doesn't work, using `replace` instead.

**Comment by dai-shi** [comment]
@barelyhuman Does this "exports" look good?

**Review by Thisen — APPROVED** [review]
LGTM

**Comment by dai-shi** [comment]
@Thisen test failed. 😱

**Comment by Thisen** [comment]
> @Thisen test failed. 😱

@dai-shi Fixed it

**Comment by barelyhuman** [comment]
@dai-shi Seems to be working with the TS Exports, which I guess was my only concern here so yeah it works! 👍🏼

**Comment by dai-shi** [comment]
Great to hear that. I will create the same PRs in zustand and valtio.

**Pull request merged**
