### PR TITLE
fix: precise SetAtom type in useAtom

### LINKED ISSUE #416: SetAtom<Update> result should be one of void or Promise<void>, not both
Currently, the type of `SetAtom<Update>` is
```ts
export declare type SetAtom<Update> = undefined extends Update ? (update?: Update) => void | Promise<void> : (update: Update) => void | Promise<void>;
```
When I call `useAtom`, it seems to me all the information is available to determine if the result of the write function will be a `Promise` or not.

It looks like this would require `WritableAtom` containing this information as a type parameter.

### PR DESCRIPTION
**Pull request by dai-shi**
close #416

### CODE REVIEW

**Comment by dai-shi** [comment]
@garrett-hopper How is this?

**Comment by garrett-hopper** [comment]
@dai-shi, hmm, doesn't quite seem to work. :thinking:
```
Type 'WritableAtom<null, FileWithPath>' is not assignable to type 'AsyncWritableAtom<null, FileWithPath>'.
  Type 'SyncWritableAtom<null, FileWithPath>' is not assignable to type 'AsyncWritableAtom<null, FileWithPath>'.
    Type 'SyncWritableAtom<null, FileWithPath>' is not assignable to type '{ write: AsyncWrite<FileWithPath>; onMount?: OnMount<FileWithPath>; }'.
      The types returned by 'write(...)' are incompatible between these types.
        Type 'void' is not assignable to type 'Promise<void>'. [2322]
```

**Comment by dai-shi** [comment]
Hmm, maybe it's not possible with this way.

**Comment by dai-shi** [comment]
On second thought, this is not precise. It can return a promise even if the atom is sync writable. We could always return a promise, but I feel like it should be optional.

**Pull request closed without merging**
