### PR TITLE
fix(weakCache): Replace recursion with while loop to avoid too much recursion

### LINKED ISSUE #630: waitForAll inside selector throws with a lot of atoms
https://codesandbox.io/s/hopeful-newton-0p6q3?file=/src/App.js

Running locally it starts throwing after 6225 atoms, on codesandbox 8000+.

I've also added a failing test in a fork.
https://github.com/fc1943s/jotai/commit/db74e3ccb01aced42a448c447741c852e40f8209

image

### PR DESCRIPTION
**Pull request by Thisen**
Fixes #630

### CODE REVIEW

**Comment by dai-shi** [comment]
Great you found a solution!
I'd like to understand the issue and possibly come up with alternative solution.

So, is this only the issue with the weakCache? If we didn't use getWeakCacheItem by commenting out, would the test pass? (well, I can try...)

**Comment by Thisen** [comment]
The issue seems to be too much recursion, JS doesn't handle that very well. Another solution would be a for loop, but I'm not sure how you would do that, given the current algorithm, where you push the item into the entry in `setWeakCacheItem`>

**Comment by dai-shi** [comment]
Oh, I see. It's recursion. Yeah, I kind of knew this would happen.
I think we can implement with for-loop. Would you like to try or want me to try?

**Review by dai-shi — APPROVED** [review]
Yay! Thanks for finding the solution and fixing it!

**Pull request merged**
