### PR TITLE
Apply publint recommendations

### PR DESCRIPTION
**Pull request by dbritto-dev**
## Related Issues or Discussions

Publint warnings -> https://publint.dev/jotai@2.5.0

## Summary

Apply publint recommendations

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
Thanks for the PR. Looks good to me. Is this still a draft?

**Comment by dbritto-dev** [comment]
@dai-shi yeah, still in draft we still getting some warnings from publint

**Comment by dbritto-dev** [comment]
@dai-shi all yours, we still getting some warnings but I guess those warnings are less important in any case you can review those warnings too

**Review by dai-shi — APPROVED** [review]
The change looks good to me.

**Pull request merged**
