### PR TITLE
docs: add `ai.mdx`

### PR DESCRIPTION
**Pull request by himself65**
## Summary

https://github.com/jotaijs/jotai-ai

This PR adds a third party section that the packages from the community.

The document hasn't been finished yet; you can give me feedback. Thanks.

## Check List

- [ ] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks for opening up a PR.
My expectation was something like https://github.com/pmndrs/zustand/blob/main/docs/integrations/third-party-libraries.md, just title and description in a line.
Let's get a feedback from @sandren .

**Comment by dai-shi** [comment]
Here's valtio one: https://github.com/pmndrs/valtio/blob/main/docs/resources/libraries.mdx

**Comment by sandren** [comment]
> Thanks for opening up a PR. My expectation was something like https://github.com/pmndrs/zustand/blob/main/docs/integrations/third-party-libraries.md, just title and description in a line. Let's get a feedback from @sandren .

Yes, I'll add a catch-all "Third-party" doc for community libraries where this material can be added to for now. But would love to see `jotai-ai` mature and then have its own separate doc in Integrations in the future. 🙂

**Comment by himself65** [comment]
Since jotai-ai has been moved to jotaijs organization, can we move it to the extension part?

**Review by himself65 — COMMENTED** [review]
I will keep this PR alone for a while, update jotai-ai itself first.

**Comment by dai-shi** [comment]
> Since jotai-ai has been moved to jotaijs organization, can we move it to the extension part?

I've decided to have three categories.
- Official lib: `pmndrs/jotai`
- Semi-official libs: `jotaijs/*` **and** listed/described in the official docs (currently as "extensions")
- Third-party libs: `jotaijs/*` or any other repos outside (we'll create a catch-all doc)

At this point, I consider `jotai-ai` as a third-party lib. But, the border between the semi-official libs and the third-party libs is vague. We consider the purpose, maturity and usage in total. There are some historical reasons and exceptions too.

---

This makes me think that we can move `jotai-zustand` and `jotai-valtio` to third-party libs.

**Pull request closed without merging**
