### PR TITLE
doc: Update terminology 'Integrations' to 'Extensions'

### PR DESCRIPTION
**Pull request by dmaskasky**
## Related Issues or Discussions
Resolves https://github.com/pmndrs/jotai/discussions/2169

## Summary
- Replace instances of integrations with extensions throughout the website documentation.
- Update navigation, headers, and section titles accordingly.
- Ensure consistency in term usage across all documentation pages.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dmaskasky** [comment]
image

**Comment by dmaskasky** [comment]
image

**Comment by dai-shi** [comment]
I didn't realize when looking at #2169, but this gives me feel "Ecosystem" is too broad. Because, "SWC", "Babel", "Devtools" in "Tools" can also be considered as ecosystem. So, maybe we want a narrower term.

**Comment by dmaskasky** [comment]
> I didn't realize when looking at #2169, but this gives me feel "Ecosystem" is too broad. Because, "SWC", "Babel", "Devtools" in "Tools" can also be considered as ecosystem. So, maybe we want a narrower term.

Hmm, what should we use instead?

**Comment by sandren** [comment]
> Hmm, what should we use instead?

Thanks for the PR! "Extensions" is the first thing that comes to mind, but I'll let others chime in with suggestions as well. 🙂

**Comment by dmaskasky** [comment]
> Thanks for the PR! "Extensions" is the first thing that comes to mind, but I'll let others chime in with suggestions as well. 🙂

21 ideas:

1. Add Ons
2. Community Add Ons
3. Community Enhancements
4. Community Extensions
5. Community Modules
6. Community Packages
7. Community Plugins
8. Ecosystem
9. Enhancements
10. Extensions
11. Modules
12. Packages
13. Plugins
14. Third-Party
15. Third-Party Add Ons
16. Third-Party Ecosystem
17. Third-Party Enhancements
18. Third-Party Extensions
19. Third-Party Modules
20. Third-Party Packages
21. Third-Party Plugins

**Comment by sandren** [comment]
@dmaskasky Let's go with "Extensions". Thanks! 🙂

**Comment by dai-shi** [comment]
@sandren Is it possible to have a redirect from `integrations` to `extensions` to avoid "404"?

**Comment by dmaskasky** [comment]
> @sandren Is it possible to have a redirect (for the website) from integrations to extensions to avoid "404"?
How is this done?

**Comment by dmaskasky** [comment]
image

**Comment by dmaskasky** [comment]
image

**Comment by sandren** [comment]
> How is this done?

Redirects are handled in `gatsby-node.js`:

```js
createRedirect({
  fromPath: `/docs/integrations/*`,
  toPath: `/docs/extensions/*`,
  isPermanent: false,
});
```

**Comment by dmaskasky** [comment]
> > How is this done?
> 
> Redirects are handled in `gatsby-node.js`:
> 
> ```js
> createRedirect({
>   fromPath: `/docs/integrations/*`,
>   toPath: `/docs/extensions/*`,
>   isPermanent: false,
> });
> ```

This didn't work for me locally. I have included this in the PR. Could you please test this?

**Comment by dmaskasky** [comment]
Also, I could use some advice with git.

I am unsure why GH is reporting a conflict with `docs/integrations/scope.mdx`. I have already rebased.
```
jotai jotai-ecosystem-docs $ git fetch && git rebase origin/main
Current branch jotai-ecosystem-docs is up to date.
jotai jotai-ecosystem-docs $ git fetch upstream && git rebase upstream/main
Current branch jotai-ecosystem-docs is up to date.
jotai jotai-ecosystem-docs $ pwd       
/Users/davidmaskasky/Code/jotai
```

**Comment by sandren** [comment]
> This didn't work for me locally. I have included this in the PR. Could you please test this?

It's not working in the deploy preview either. I think we'll need to add an explicit redirect for reach integration -> extension like the utils redirects above.

**Comment by dmaskasky** [comment]
> > This didn't work for me locally. I have included this in the PR. Could you please test this?
> 
> It's not working in the deploy preview either. I think we'll need to add an explicit redirect for each integration -> extension like the utils -> utilities redirects above.

That sounds like an unnecessary maintenance burden. Wildcards should work, not sure why they don't though. I don't have a lot of experience with Gatsby.

**Pull request closed without merging**
