### PR TITLE
fix(examples): import issue and upgrade to v2

### PR DESCRIPTION
**Pull request by milhamm**
## Related Issues or Discussions

Fixes https://github.com/pmndrs/jotai/issues/1890

## Summary

After trying and fixing the issue, I encountered another error when trying to start the app. To fix that issue, I added the rule to each examples.

```json
 "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
```

I also updated the showcases to v2 except for `todos_with_atomFamily` since I can't figure out how to do the `serializeAtom` in v2.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dai-shi** [comment]
> I can't figure out how to do the `serializeAtom` in v2.

What's blocking?
If it's about typing, we should type for `action`.
```ts
const serializeAtom = atom(null, (get, set, action: ...) => { 
```

**Comment by milhamm** [comment]
Hey @dai-shi. Thanks for the help. Yea, it was a typing issue and it's fixed.

About the linting error. Is it okay for me to add `"ignorePatterns": ["examples/*"]` to the `.eslintrc.json`?
I'm unsure how to make the examples work without the newly added rules on each `package.json` and I feel like it's safe to ignore it since its "not quite related" to the core library

**Comment by dai-shi** [comment]
> I think the code sandbox example from https://jotai.org/docs/guides/persistence needs to be updated to v2 too

Yes, please fork it and update it.

> About the linting error. Is it okay for me to ignore the ./example/* path on for the linting ci scripts? `"eslint '*.{js,json}' '{src,tests,benchmarks}/**/*.{ts,tsx}' --ignore-pattern 'examples/*'"`
> 
> The issue here is that the extend "react-app" config is only available when we `yarn install` the example app

Can you do the same as https://github.com/pmndrs/zustand/pull/1754 by @arjunvegda ?

**Comment by milhamm** [comment]
Thanks for the reference, I've updated it and it works fine.

**Comment by milhamm** [comment]
I will create a separate PR to update the docs if that's okay for you @dai-shi.

**Review by dai-shi — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
