### PR TITLE
fix(types): useAtom with one type argument for primitive atoms

### PR DESCRIPTION
**Pull request by dai-shi**
This has been asked several times. Hope this doesn't break some usages.

### CODE REVIEW

**Comment by hatemhosny** [comment]
It seems Jotai is not being bundled.

The GitHub action will not bundle the files, it can just make them available as data urls.

The import map was indeed loaded. You can view project json: app menu -> export -> export project (json)

It looks like this:
```json
{
...
"imports": {
    "jotai": "data:application/javascript;charset=UTF-8;base64,ZXhwb3J0ICogZnJvbSAnam90YWkvdmFuaWxsYSc7CmV4cG9ydCAqIGZyb20gJ2pvdGFpL3JlYWN0JzsK"
  },
...
}
```

The data url is loaded like that:

```js
export * from 'jotai/vanilla';
export * from 'jotai/react';
```

Which gives the error message. 

You can either:
- bundle the files (in the `build-command` input) and load the bundle
- add all the used files in the imports as data urls
- deploy the files to a preview environment and use `{{LC::TO_URL(./file.js)}}` pattern, then relative imports can work

If you want the import map to appear in UI (custom settings) put the `imports` property inside `customSettings` property, like this:

```json
{
  ...
  "customSettings": {
    "imports": {
      "jotai": "..."
    }
  },
  ...
}
```

**Comment by dai-shi** [comment]
@hatemhosny 
Thanks.
Yes, we need to build it.

> If you want the import map to appear in UI

No, I don't need that.

**Comment by dai-shi** [comment]
#2387

**Comment by dai-shi** [comment]
#2388

**Comment by dai-shi** [comment]
> ## [LiveCodes](https://livecodes.io) Preview in [LiveCodes](https://livecodes.io)
> **Latest commit:** [87637f2](https://github.com/pmndrs/jotai/commit/87637f2fd22fbf6f7e222da4fe1a01ecf27ea686) **Last updated:** Feb 10, 2024 1:04am (UTC)
> 
> Playground	Link
> **React demo**	https://livecodes.io?x=id/GA8SB847X
> _See [documentations](https://github.com/live-codes/preview-in-livecodes) for usage instructions._

Works now! 🎉

**Comment by dai-shi** [comment]
I wonder if the action works from forked repo, though. Will see.

**Comment by hatemhosny** [comment]
> Works now! 🎉

Very nice  🎉

> I wonder if the action works from forked repo, though. Will see.

I will do a test PR to demonstrate that from an account with no permissions on your repo.

**Comment by hatemhosny** [comment]
> > I wonder if the action works from forked repo, though. Will see.
> 
> I will do a test PR to demonstrate that from an account with no permissions on your repo.

It works :)
https://github.com/pmndrs/jotai/pull/2389#issuecomment-1936891730

**Comment by dai-shi** [comment]
> > If you want the import map to appear in UI
> 
> No, I don't need that.

@hatemhosny 
Actually, we need to know which commit is used in the UI, and it would be nice if we can revert it back to the npm version.
So, we should make it appear in UI.

**Pull request merged**
