### PR TITLE
no implicit peer dependency

### PR DESCRIPTION
**Pull request by dai-shi**
ref: https://github.com/pmndrs/jotai/issues/135#issuecomment-710782084 https://github.com/pmndrs/jotai/pull/139#discussion_r506916713

### CODE REVIEW

**Comment by dai-shi** [comment]
@merceyz I guess this fixes for react-dom users, but for react-native users we should add `react-native` as an optional dependency, shouldn't we?

**Comment by merceyz** [comment]
Correct, I would like it if you could update the install instructions to not be Yarn 2 specific as well though

**Comment by dai-shi** [comment]
@merceyz If you are still around, would you check the changes?

**Review by merceyz — APPROVED** [review]
Perfect, thank you :)

**Pull request merged**
