### PR TITLE
fix: avoid triggering state change call when restoring state

### PR DESCRIPTION
**Pull request by arjunvegda**
## Summary
- Skip triggering `state` change callback when restoring the state

## Check List

- [x] `yarn run prettier` for formatting code and docs
- [ ] Get Daishi's feedback
- [ ] Add tests

### CODE REVIEW

**Comment by dai-shi** [comment]
> Skip triggering state change callback when restoring the state

Hi, I'm curious the reason behind it. Is it because your devtools initiates `restore`, or someone does it just in case? If you initiate it, you know it so you can mute your listeners.

**Comment by arjunvegda** [comment]
> Is it because your devtools initiates `restore`

That is precisely it! 

> If you initiate it, you know it so you can mute your listeners

Yeah, I tried taking that route. However, I'm not sure how to unmute them back without relying on if the value changed 😅 

So I figured that it would be nice to have `dev_subscribe_store` differentiate between different types of changes

**Comment by dai-shi** [comment]
(Actually, restore is v2 isn't a real "restore" which was the case in v1. it's just bulk write. "write" can be async... I'll see what I can do in #1966)

**Comment by dai-shi** [comment]
Closing in favor of #1966.

**Pull request closed without merging**
