### PR TITLE
Update primitives.mdx

### PR DESCRIPTION
**Pull request by AjaxSolutions**
I believe useMemo should be wrapped in useAtom in this example.

### CODE REVIEW

**Review by dai-shi — APPROVED** [review]
Good catch.

**Comment by dai-shi** [comment]
Please run `yarn run prettier`.

**Comment by AjaxSolutions** [comment]
I used prettier.  Hopefully this looks better.

**Comment by dai-shi** [comment]
You are not using the right config. Can't you run `yarn run prettier`?

**Comment by AjaxSolutions** [comment]
I'm using a Mac computer which is not mine.  I can't make too many changes on this Mac.  Is there a simple way to run prettier?

**Comment by dai-shi** [comment]
> I'm using a Mac computer which is not mine. I can't make too many changes on this Mac. Is there a simple way to run prettier?

I'm not sure what you mean. `yarn` is not installed? How about `npm run prettier`?

**Pull request merged**
