### PR TITLE
type file for utils.cjs

### LINKED ISSUE #73: import from 'jotail/utils' throwing an error
```ts
import { useUpdateAtom } from 'jotai/utils'
```

I'm using Next.js and when I try to import from `jotai/utils` it's throwing this error:

Screenshot 2020-09-30 at 16 30 24

### PR DESCRIPTION
**Pull request by dai-shi**
close #73.

~breaking change: `*.cjs.js` are renamed to `*.cjs`~

~also adds `*.mjs` (the same content as `*.js`) for node12.~

It simply adds types for `utils.cjs`.

### CODE REVIEW

**Comment by dai-shi** [comment]
@Kerumen

Install the bundle by codesandbox ci and please try all patterns.
```js
import { useUpdateAtom } from 'jotai/utils'
import { useUpdateAtom } from 'jotai/utils.js'
import { useUpdateAtom } from 'jotai/utils.cjs
import { useUpdateAtom } from 'jotai/utils.mjs''
```

**Comment by Kerumen** [comment]
@dai-shi it broke the default export:

Screenshot 2020-10-02 at 14 08 58

**Comment by dai-shi** [comment]
But, I didn't change the `index.js` file 🤯 

```js
import ... from 'jotai/index.mjs'
```
might help?

**Comment by Kerumen** [comment]
Nope.

Screenshot 2020-10-02 at 14 31 43

**Comment by dai-shi** [comment]
https://codesandbox.io/s/jotai-next-typescript-rme4f?file=/pages/index.tsx
Finally, it works. I gave up mjs, it's too tricky.

**Pull request merged**
