### PR TITLE
docs: typo in some files

### PR DESCRIPTION
**Pull request by sepehr-safari**
1) Fixed typo "embeded" to "embedded"
2) Fixed typo "identifer" to "identifier".
3) Fixed typo "limmited" to "limited".
4) Fixed typo "dependants" to "dependents".
5) Fixed typo "recursivly" to "recursively".
6) Fixed typo "seperate" to "separate".
7) Fixed typo "gastby" to "Gatsby".
8) Fixed typo "retreiving" to "retrieving".
9) Fixed typo "retreival" to "retrieval".

### CODE REVIEW

**Comment by dai-shi** [comment]
Hi, can you please combine docs typo fixing PRs into one PR?

**Comment by sepehr-safari** [comment]
> Hi, can you please combine docs typo fixing PRs into one PR?

Hi, It's done.

**Comment by AjaxSolutions** [comment]
> Fixed typo "gastby" to "Gatsby".

Good list.  We might as well change jotai to Jotai on this page.

https://github.com/pmndrs/jotai/blob/a15523f27822bef50887a60693429637ccbb5e32/examples/hacker_news/README.md#L5

**Review by dai-shi — APPROVED** [review]
Thanks!

**Pull request merged**
