### PR TITLE
Continuation of fix(utils/atomWithDefault): support refresh

### PR DESCRIPTION
**Pull request by LucaColonnello**
Continuation of pmndrs#537

### CODE REVIEW

**Comment by LucaColonnello** [comment]
@dai-shi the origin branch needs a rebase with master (which I did here).
I've added the tests for both the sync and async examples.

I looked around but I just can't find where the docs files are, but I'm happy to add documentation if you can point me in the right place :)

**Comment by dai-shi** [comment]
docs are in the separate repo (for now): https://github.com/pmndrs/website/blob/docs/docs/jotai/api/utils.mdx

**Comment by LucaColonnello** [comment]
Aaaah thanks, I looked at that one but couldn't find it, probably should have looked better :( thanks!

**Comment by dai-shi** [comment]
Hmm, I rebased pmndrs:fix/issue-521 from master. You would need to rebase your branch from pmndrs:fix/issue-521?

**Comment by LucaColonnello** [comment]
It shouldn't need to, if you look at the files changes now they are aligned

**Comment by dai-shi** [comment]
Hm, I reverted my previous push... Now, what should we do to clean src/utils changes?

**Comment by dai-shi** [comment]
I could merge 25be8862a98e7f3fef9bbf638341f35a397258b6. Let me try.

**Comment by LucaColonnello** [comment]
Sorry I'm missing what's the problem here?

**Comment by dai-shi** [comment]
I expected this PR to only show changes in test files.

**Comment by dai-shi** [comment]
Never mind. Just a subtle thing. Let me merge this.

**Pull request merged**
