### PR TITLE
chore: onUpdate

### PR DESCRIPTION
**Pull request by L-Qun**
## Summary
We have a requirement where certain actions are triggered when the state of an atom changes. Therefore, we added onUpdate, corresponding to onMount.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by AjaxSolutions** [comment]
> We have a requirement where certain actions are triggered when the state of an atom changes. Therefore, we added onUpdate, corresponding to onMount.

Why is it called onUpdate as opposed to onChange?

**Comment by L-Qun** [comment]
> > We have a requirement where certain actions are triggered when the state of an atom changes. Therefore, we added onUpdate, corresponding to onMount.
> 
> Why is it called onUpdate as opposed to onChange?

I think calling it onChange would also be good.

**Comment by L-Qun** [comment]
> I noticed that [Reatom](https://www.npmjs.com/package/@reatom/npm-react) atoms have the onChange method which returns a cleanup function.
> 
> `const cleanup = itemAtom.onChange((ctx, state) => setValue(state))`
> 
> Calling this cleanup function removes the callback from the atom's listeners(?)

These two are not the same. In Reatom, onChange is implemented by the framework, but onUpdate is implemented by the user themselves and does not require a return of onUpdate.

**Comment by AjaxSolutions** [comment]
Thanks.  Also, the [doc](https://jotai.org/docs/core/atom#), should be updated.

**Comment by dai-shi** [comment]
We specifically avoid adding `onUpdate` as a design principle #211. While we might add it in the future (Jotai v3?), for now, we suggest [jotai-effect](https://github.com/jotaijs/jotai-effect) which is developed on the current API.

**Pull request closed without merging**
