### PR TITLE
fixes #177: use areEqual in atom remove

### LINKED ISSUE #177: atomFamily.remove should follow areEqual
atomFamily's createAtom.remove should follow areEqual if it is specified.
ref: https://github.com/pmndrs/jotai/pull/176#discussion_r519700888

Preferably with tests.

### PR DESCRIPTION
**Pull request by likern**
fixes #177

### CODE REVIEW

**Comment by dai-shi** [comment]
Hi, thanks for the work.

Do we really need to reject `undefined` param?

```js
    if (areEqual === undefined) {
      atoms.delete(param)
    } else {
      for (let [key, _] of atoms) {
        if (areEqual(key, param)) {
          atoms.delete(key)
          break
        }
      }
    }
```

Does this work?

A minor note:  Does `[key]` work instead of `[key, _]`?

**Comment by likern** [comment]
> Hi, thanks for the work.
> 
> Do we really need to reject `undefined` param?
> 
> ```js
>     if (areEqual === undefined) {
>       atoms.delete(param)
>     } else {
>       for (let [key, _] of atoms) {
>         if (areEqual(key, param)) {
>           atoms.delete(key)
>           break
>         }
>       }
>     }
> ```
> 
> Does this work?
> 
> A minor note: Does `[key]` work instead of `[key, _]`?

Yes, we can allow `undefined`. Initially I've written code as you, but then decided to rewrite. I can update PR.
`[key]` will also work. Can update too.

**Comment by dai-shi** [comment]
If there's no drawbacks, please update. There wouldn't be any specific use case of `undefined`, but I don't prefer having the if-undefined-throw statement.

**Review by dai-shi — APPROVED** [review]
Looks good. Thanks for your quick work.

**Pull request merged**
