### PR TITLE
atomWithMutation

### PR DESCRIPTION
**Pull request by Aslemammad**
- atomWIthMutation
- tests

### CODE REVIEW

**Comment by Aslemammad** [comment]
@aulneau, I think I will work on other parts; feel free to work on this part. Thank you.

**Comment by dai-shi** [comment]
happy to see you guys start collaborating. the original issue is #309, but no context there anyway.

**Comment by Aslemammad** [comment]
Thanks, @dai-shi, @aulneau. If you have any question, aslemammad#6670 is my discord.

**Comment by dai-shi** [comment]
Let me close this for now and discuss in #309.

**Pull request closed without merging**
