### PR TITLE
allow edge case of client being null on urql atoms

### PR DESCRIPTION
**Pull request by israelidanny**
This solves https://github.com/pmndrs/jotai/issues/622 and adds a test for this edge case.

- [x] test for `atomWithQuery` to work properly when `client` is switched 
- [x] test for `atomWithSubscription` to work properly when `client` is switched 
- [x] throw a promise in `atomWithQuery` if `client === null`
- [x] throw a promise in `atomWithSubscription` if `client === null`
- [x] test for `atomWithQuery` to work properly when `client` is toggled to null
- [x] test for `atomWithSubscription` to work properly when `client` is toggled to null 

This PR expands on https://github.com/pmndrs/jotai/pull/634, and if this one is merged then 634 can be closed as this one has all of those tests as well.

### CODE REVIEW

**Comment by dai-shi** [comment]
Sorry, if I rushed you with a hacky solution. To me, this is a last resort, and I would like to avoid this if possible. People wouldn't expect an atom to suspend if client is null. Or would they.

So, I think we should explore two things before this.

1. can we somehow pass non-null client if that's recommended in urql? (this is a doc issue)
2. I hope the guard originally proposed in #622 to work, or understand why it can't be fixed. (this is probably jotai core issue)

if 2) is really jotai core issue rather than jotai/urql issue, it's a broader issue we should investigate.

**Comment by israelidanny** [comment]
As far as (1) goes, I am fairly confident that setting client to null is
not a urql pattern.

Rather, the expectation is to keep the client but avoid mounting a
component that does `useSubscription` or `useQuery`. Alternatively there is
also a `pause` prop on the hooks. We could perhaps implement the `pause`?

**Comment by dai-shi** [comment]
Yeah, `pause=true` is much better than `client=null`.

We had some discussions about it: https://github.com/pmndrs/jotai/pull/463#discussion_r628814676

**Comment by israelidanny** [comment]
I'm not totally convinced that this is very urgent to build. I'm actually doing quite fine in my app without ever having to set `client` to null (by guarding against displaying any components / screens that require auth). If someone desperately needs to set client to null, there is the hack you proposed. 

Do you think this is really important to be solved on library level?

I think this could be closed & we could focus on investigating why the original guard fails (potential core bug)

**Comment by dai-shi** [comment]
> I think this could be closed & we could focus on investigating why the original guard fails (potential core bug)

Yes, that's what I meant in https://github.com/pmndrs/jotai/pull/635#issuecomment-891492347.

**Pull request closed without merging**
