### PR TITLE
docs(DevTools): add note about @emotion/react + misc. updates

### PR DESCRIPTION
**Pull request by arjunvegda**
- Relevant PR https://github.com/jotaijs/jotai-devtools/pull/42
- Ready to be merged at any time

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by sandren** [comment]
@arjunvegda Thanks for update! ☺️

Could `@emotion/react` be moved to a direct dependency of `jotai-devtools` instead of a peer dependency? Also the docs should install `jotai-devtools` with the `-D` flag since it isn't used in production builds.

**Comment by arjunvegda** [comment]
> @arjunvegda Thanks for update! ☺️
> 
> Could `@emotion/react` be moved to a direct dependency of `jotai-devtools` instead of a peer dependency? Also the docs should install `jotai-devtools` with the `-D` flag since it isn't used in production builds.

Thanks for taking a look! 🙏 

> Could `@emotion/react` be moved to a direct dependency of `jotai-devtools` instead of a peer dependency?

We moved away from that approach [recently](https://github.com/jotaijs/jotai-devtools/pull/42). We realized that it may cause issues like [these](https://github.com/Tintef/react-google-places-autocomplete/issues/176) where it loads multiple instances of the library if the user relies on `@emotion/react` on their end.

The maintainers [recommend](https://github.com/emotion-js/emotion/issues/2343#issuecomment-817265816) using it as a peer dependency too.

> Also the docs should install `jotai-devtools` with the `-D` flag since it isn't used in production builds

I thought about it, but it's not fully dev-only unlike `eslint`, `jest`, etc. They'll have to strip out the `jotai-devtools` code when they build a prod bundle to fully use `yarn install --production` otherwise, it'll throw reference errors on their production builds which may lead to confusion 😅

**Comment by sandren** [comment]
@arjunvegda Thanks for those details. I'll go ahead and merge your changes, but in the future, we should see if `jotai-devtools` can be refactored to avoid such a heavy peer dependency. Thanks!

**Comment by nicobatalla** [comment]
The problem with this is that if you're using any other styling solution out there + `jotai` + `jotai-devtools` you are forced to install `@emotion/react` in your product even if your app is not using it at all. 

Direct dependency was better IMO

**Comment by arjunvegda** [comment]
> The problem with this is that if you're using any other styling solution out there + `jotai` + `jotai-devtools` you are forced to install `@emotion/react` in your product even if your app is not using it at all.
> 
> Direct dependency was better IMO

Is installation the only concern or did we run into any interop issues? We wanted to cater to users using `emotion` as their primary styling solution, too, and prevent version mismatch issues for them. 

FWIW, we're planning to move towards a native CSS solution and move away from`@emotion/react in the long term.

**Comment by nicobatalla** [comment]
There should not be any interoperation issues but the build is failing on the jotai-devtools version update PR in our repo because we don't have `@emotion/react` installed.  In our case we are using `styled-components`, so we don't really need `emotion`. 

The previous approach was fine because it was tree-shaken anyway, but now we are forced to install `emotion` too if we want to update.

**Comment by arjunvegda** [comment]
> There should not be any interoperation issues but the build is failing on the jotai-devtools version update PR in our repo because we don't have `@emotion/react` installed. In our case we are using `styled-components`, so we don't really need `emotion`.
> 
> The previous approach was fine because it was tree-shaken anyway, but now we are forced to install `emotion` too if we want to update.

Gotcha! We should still be okay from the tree-shaking standpoint, no? Or are you running into any issues there?

If it's a blocker for your workflow, I can try identifying a few workarounds that you could use on your end, until we completely move towards a native CSS solution.

**Comment by nicobatalla** [comment]
Need to check if the bundle size would be increased, but we would definitely prefer not having to install emotion at all if possible.

Any ETA on the move to native CSS?

**Pull request merged**
