### PR TITLE
docs(initialize-atom-on-render): migrate codesandbox code to v2

### PR DESCRIPTION
**Pull request by t6adev**
The updated code is following [the migration guide](https://jotai.org/docs/guides/migrating-to-v2-api).

### CODE REVIEW

**Comment by t6adev** [comment]
On this page, this line's `store={storeRef.current}` should be removed?
```
<Provider store={storeRef.current}>
```

**Comment by dai-shi** [comment]
> On this page, this line's `store={storeRef.current}` should be removed?
> 
> ```
> <Provider store={storeRef.current}>
> ```

Yeah, I think it's a leftover.

**Review by dai-shi — APPROVED** [review]
LGTM

@sandren

**Review by sandren — APPROVED** [review]

**Comment by sandren** [comment]
Thank you! ☺️

**Pull request merged**
