### PR TITLE
breaking(build): drop module condition in exports

### PR DESCRIPTION
**Pull request by dai-shi**
"module" condition was added for non-native ESM to possibly support old bundlers.
Not sure, if/how it's used. Maybe, it was added for webpack 4, but not required for v2.

### CODE REVIEW

**Comment by dai-shi** [comment]
what do you think? @barelyhuman

**Comment by barelyhuman** [comment]
This was added for snowpack if I remember properly, since it didn't pick up the `import` key, let me see if it can pick it up now and we should be able to move forward with this, also , reminder, don't trust the codesandbox for this since it's flaky for snowpack package resolutions

**Comment by barelyhuman** [comment]
Confirmed, 
Seems to be working 👍🏼

**Comment by dai-shi** [comment]
Checking https://github.com/pmndrs/jotai/discussions/1756 if this is related.

**Pull request merged**
