### PR TITLE
docs(fast refresh): introduce dx issue

### PR DESCRIPTION
**Pull request by TwistedMinda**
Following-up to [issue #1025](https://github.com/pmndrs/jotai/issues/1025)

Quick reminder: goal is to have some kind of "official statement" of the status with Fast Refresh:

- current workaround: as long as you don't modify a file that contains the atom declaration, it will not reset the state
- our feeling: DX not the best, forcing to split atoms to avoid state reset, but we are aware/working on it
- can be very hard to understand why it got reset in some situations
- we're very much open to support/contribution on this
- (edit) can fix instantly with babel plugin!

### CODE REVIEW

**Comment by dai-shi** [comment]
I think you miss `jotai/babel/plugin-react-refresh`.

With the plugin, fast refersh should work for globally defined atoms even if they are in the same file.

**Comment by TwistedMinda** [comment]
@dai-shi No, unfortunately I do have `jotai/babel/plugin-react-refresh`.
Maybe I did bad at setting it up?
I have followed the docs by updating my babel.config.js & restarting my metro bundler: 
```json
{
  "plugins": ["jotai/babel/plugin-react-refresh"]
}
```
Do I miss anything?

**Comment by dai-shi** [comment]
> @dai-shi No, unfortunately I do have `jotai/babel/plugin-react-refresh`. Maybe I did bad at setting it up? I have followed the docs by updating my babel.config.js & restarting my metro bundler:

Then, it's not a doc issue, but a real issue for the plugin.

> Do I miss anything? Note: I'm using React-Native, does that change anything?

Can you try checking the behavior with codesandbox first?
We are not yet sure where the problem is. #1025 is an issue we wanted to hear details.

Meanwhile, let's hold this PR as it may not be accurate.

**Comment by TwistedMinda** [comment]
@dai-shi Okay I think it was the good old mistake:
I had 
```ts
{
  "plugins": [
     ["jotai/babel/plugin-react-refresh"]
  ]
}
```
instead of
```ts
{
  "plugins": ["jotai/babel/plugin-react-refresh"]
}
```

Works perfectly now. I'm confused now, what is the problem with FastRefresh then ? And should we still do a FastRefresh page to at least mention that the plugin has to be used in order to avoid a reset ?

**Comment by alan-nf** [comment]
@dai-shi if you look at my original repro in https://github.com/pmndrs/jotai/issues/1150 you can see that the jotai atom gets reset if it's included in the bundles that are hot-updated. If that's not intended behavior I can re-open https://github.com/pmndrs/jotai/issues/1150. Can you let me know?

(And before anyone asks, the code sandbox is using create-react-app which uses react refresh under the covers. See [this post](https://github.com/pmndrs/jotai/issues/1150#issuecomment-1124152252) for more info)

**Comment by Thisen** [comment]
Closing this, as it has been resolved in 1.7.3.

**Pull request closed without merging**
