### PR TITLE
Try using function toString for map key

### LINKED ISSUE #1025: Problems with React Fast Refresh
Hi, while it works well in most cases, we experience some bugs.

1. Editing functions out of react tree aren't updated. For example, update the logic of your read-only atom and issue a state update.
2. The referential integrity of the atom store gets broken. I receive no longer state updates. I need to reload to fix it.

All issues happen when using react fast refresh with https://github.com/gsoft-inc/craco. We use the jotai babel preset as documented on the website!

Thank you and keep up the good work!

### PR DESCRIPTION
**Pull request by Thisen**
Implementation is an experiment. Lets see.

Closes #1025.

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
the change looks okay.

**Comment by dai-shi** [comment]
@Thisen I was trying to test this, but before going into it, found the original codesandbox example doesn't work.
https://codesandbox.io/s/priceless-benz-bgf3b in https://jotai.org/docs/api/babel

Do you know what causes it?

**Comment by Thisen** [comment]
I can check it out, but since we can't support the issue fully, I think we should just close. WDYT @dai-shi ?

**Comment by dai-shi** [comment]
I still don't understand the real issue in #1025. Can you help with [the comment](https://github.com/pmndrs/jotai/issues/1025#issuecomment-1062362840)?

On the other hand, this PR seems reasonable and valuable.
Do you think if you can create a codesandbox example that fails without this PR, and will be fixed by this PR?

**Comment by Thisen** [comment]
Closing due to somewhat hacky solution. Can re-open if we decide otherwise.

**Pull request closed without merging**
