### PR TITLE
[tentative] website for docs with next mdx

### PR DESCRIPTION
**Pull request by dai-shi**
Would anyone like to work on it?

### CODE REVIEW

**Comment by Aslemammad** [comment]
Let me check if I can.

**Comment by Thisen** [comment]
Great choice of stack. ;)

**Comment by dai-shi** [comment]
> Great choice of stack. ;)

I like it having `docs` outside.
Unfortunately, I don't think I can finish this especially for styling it pretty. Hope someone can jump in.

**Comment by Thisen** [comment]
> > Great choice of stack. ;)
> 
> I like it having `docs` outside.
> Unfortunately, I don't think I can finish this especially for styling it pretty. Hope someone can jump in.

Could some Poimandres people help?

**Comment by dai-shi** [comment]
Might be better to ask in Discord.
We need someone who has huge motivation.
Somebody were showing some interests.

**Comment by CodyJasonBennett** [comment]
We were cooking up something for [docs.pmnd.rs](https://docs.pmnd.rs) that might be worth a look ([repo here](https://github.com/pmndrs/website/tree/docs)).

**Comment by dai-shi** [comment]
https://nextra.vercel.app/ 👀

**Comment by aulneau** [comment]
@dai-shi I'll take this on, will try to open a PR this weekend or early next week if possible. I'm planning on rolling a next.js site that is very similar in nature to https://nextra.vercel.app/, but with some custom features. Is there any preference for how the app gets styled? I have a preference for css-in-js, and if there is no specific requirements, I'll use https://github.com/atlassian-labs/compiled.

**Comment by dai-shi** [comment]
css-in-js is good. i don't think there's any specific requirements about css-in-js.

**Comment by Thisen** [comment]
Just a suggestion, what about using Tailwind? It's very popular and Next.js will have first-class Tailwind support soon: https://github.com/vercel/next.js/discussions/20030

And if you want to use CSS-in-JS, you can use https://github.com/tw-in-js/twind

**Comment by dai-shi** [comment]
(I have no experience in tailwind. Another thing I need to learn.)

**Comment by Thisen** [comment]
> (I have no experience in tailwind. Another thing I need to learn.)

It's very popular, especially with Next.js.

**Comment by dai-shi** [comment]
Let me merge this into master so that I can configure vercel.
This is just tentative and I expect @aulneau will replace `website` folder completely.

**Pull request merged**
