### PR TITLE
fix(core): refactor store with suspense promise

### PR DESCRIPTION
**Pull request by dai-shi**
This includes various refactors.

- interruptable promise -> suspense promise
- eliminate prepareNextAtomState
- simplify setting promise on write (this changes the behavior slightly)

### CODE REVIEW

**Comment by dai-shi** [comment]
Oh no, CI fails with react 16.8.6. Can't figure out what's wrong. Wonder if anyone has ideas.

**Comment by Thisen** [comment]
It looks like it gets stuck in `atomWithQuery.test.tsx`. Why, I don't know. However, a bunch of these are thrown when running the tests with `react@16.8.6` + `react-dom@16.8.6`:
```
It looks like you're using a version of react-dom that supports the "act" function, but not an awaitable version of "act" which you will need. Please upgrade to at least react-dom@16.9.0 to remove this warning
```

I did a small commit that fixed minor typos, I hope that's ok.

**Comment by dai-shi** [comment]
Thanks for the fix! The act warning was there from the beginning. Not sure if resolvable. I see it gets stuck even with `tests/async.test.tsx`.

**Comment by dai-shi** [comment]
It turns out there was a bug in my refactor (I did the whole refactor again one by one with running tests in 16.8.6). What a relief. Thanks for looking into it.

**Pull request merged**
