### PR TITLE
update use-context-selector for rn

### LINKED ISSUE #81: unable to resolve `react-dom` when used with react-native ?
Screen Shot 2020-10-03 at 1 39 16 PM

it seem to be an issue with `use-context-select` @dai-shi .

### PR DESCRIPTION
**Pull request by dai-shi**
close #81

### CODE REVIEW

**Comment by dai-shi** [comment]
@a-eid Would you try the bundle by codesandbox ci to see if it works?

**Comment by a-eid** [comment]
@dai-shi I got this error 

```
error: Error: While trying to resolve module `jotai` from file `/Users/ahmedeid/code-playground/fishbowl/src/App.tsx`, the package `/Users/ahmedeid/code-playground/fishbowl/node_modules/jotai/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/ahmedeid/code-playground/fishbowl/node_modules/jotai/index.cjs.js`. Indeed, none of these files exist:

* /Users/ahmedeid/code-playground/fishbowl/node_modules/jotai/index.cjs.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/ahmedeid/code-playground/fishbowl/node_modules/jotai/index.cjs.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/ahmedeid/code-playground/fishbowl/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
``` 

I believe this output is related to `jotai`
Screen Shot 2020-10-03 at 3 46 31 PM

**Comment by a-eid** [comment]
@dai-shi okay, nevermind the above comment, it works. I installed the ci version & it's working great. 👍

**Comment by dai-shi** [comment]
Thanks for testing. Merging this.

**Pull request merged**
