### PR TITLE
chore(benchmark): fix tool for v2

### PR DESCRIPTION
**Pull request by dai-shi**
Continuing from #486.

### CODE REVIEW

**Comment by dai-shi** [comment]
with v1

```bash
./benchmarks/simple-read.ts
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/simple-read-*.json

"atoms=100",14769438
"atoms=1000",14837075
"atoms=10000",14709936
"atoms=100000",14099252
"atoms=1000000",9310498
```

```bash
./benchmarks/simple-write.ts
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/simple-write-*.json

"atoms=100",2693631
"atoms=1000",2475901
"atoms=10000",2446965
"atoms=100000",2079688
"atoms=1000000",1920391
```

```bash
./benchmarks/subscribe-write.ts
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/subscribe-write-*.json

"atoms=100",1064046
"atoms=1000",1013762
"atoms=10000",835802
"atoms=100000",786982
"atoms=1000000",559171
```

image

**Comment by dai-shi** [comment]
with v2

```bash
./benchmarks/simple-read.ts
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/simple-read-*.json

"atoms=100",14993449
"atoms=1000",14961748
"atoms=10000",14936096
"atoms=100000",14138316
"atoms=1000000",11031104
```

```bash
./benchmarks/simple-write.ts
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/simple-write-*.json

"atoms=100",3275990
"atoms=1000",3111157
"atoms=10000",2467172
"atoms=100000",2996341
"atoms=1000000",2419600
```

```bash
./benchmarks/subscribe-write.ts
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/subscribe-write-*.json

"atoms=100",1559262
"atoms=1000",1515520
"atoms=10000",1533187
"atoms=100000",1430582
"atoms=1000000",1142329
```

image

**Comment by L-Qun** [comment]
When I execute `yarn && ./benchmarks/simple-write.ts`, I encounter an error. Are there any other steps I should take?


import { add, complete, cycle, save, suite } from 'benny';
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by dai-shi** [comment]
Thanks for reporting. Looking into it.

**Pull request merged**
