### PR TITLE
test: use screen exposed by React Testing Library

### PR DESCRIPTION
**Pull request by kretajak**
## Summary

Tests using React Testing Library to should use screen instead of queries returned by `render`.

## Check List

- [x] `pnpm run prettier` for formatting code and docs

### CODE REVIEW

**Comment by kretajak** [comment]
Such changes can be enforced by [eslint-plugin-testing-library](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library/).

**Comment by dai-shi** [comment]
Thanks for working on it. I guess we would like to have the same change for Zustand and valtio.

**Comment by kretajak** [comment]
> Thanks for working on it. I guess we would like to have the same change for Zustand and valtio. Can you open PRs there too?

Hi. PR are now ready to be reviewed: 
* https://github.com/pmndrs/zustand/pull/2832
* https://github.com/pmndrs/valtio/pull/989

**Review by dai-shi — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
