### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Luccasoli**
just making it clearer where countAtom came from in this example

### CODE REVIEW

**Comment by Thisen** [comment]
Not a bad idea. 👍🏼

**Review by Thisen — APPROVED** [review]

**Comment by dai-shi** [comment]
@Luccasoli Hey, thanks for the suggestion.
That was actually somewhat intentional. (We want to keep readme compact if possible)
My question is: did you have a difficulty or confusion with the implicit example?
We could probably accept this suggestion, but I'd like to learn your opinion.

**Comment by Luccasoli** [comment]
@dai-shi I like the idea of "copy-paste" examples provided for a library to test, and I believe that when I do this and the code doesn't work it already causes frustration for the dev

So the idea of this PR is to make this example "self-sufficient" to execute

(And I didn't actually use this lib, I just saw it on twitter and I showed up here now to take a look at Readme.md, and I only identified this example that wouldn't run just by copying and pasting)

**Comment by dai-shi** [comment]
> the idea of "copy-paste" examples

Good point. But then, this alone doesn't accomplish the goal.
The current readme is really shaved to reduce size, so copy-paste is mostly impossible.
Let me hold this suggestion for now. We are working on new introduction web site where it would fit better with copy-paste examples idea.

> (And I didn't actually use this lib, I just saw it on twitter and I showed up here now to take a look at Readme.md, and I only identified this example that wouldn't run just by copying and pasting)

That's great to hear! Look forward to hearing more feedback.

Our docs repo is now at https://github.com/pmndrs/website/tree/docs/docs/jotai
where we need more help to improve docs.

**Comment by Luccasoli** [comment]
@dai-shi Got it, and it really seems to have great examples in that repository! I already know then that the documentation site will be great!

I wish success with lib! And thanks for the quick responses, it is certainly a great attraction for any dev to know that those responsible are so active in the repository!

**Pull request closed without merging**
