### PR TITLE
docs(website): add documentation for atomWithHash options

### PR DESCRIPTION
**Pull request by notsidney**
Hi, while researching atomWithHash, I found the PR that added options (#758) but they were not documented on the site. I’ve added documentation for options.

### CODE REVIEW

**Comment by notsidney** [comment]
Also, I read your comments saying you were thinking of removing atomWithHash altogether. Please don’t! I find it very useful and am now using it as part of [Rowy](https://github.com/rowyio/rowy)

**Review by dai-shi — APPROVED** [review]
Welcome to the jotai docs team!!
Thanks for working on it. Merging this.

**Comment by dai-shi** [comment]
> Also, I read your comments saying you were thinking of removing atomWithHash altogether. 

At that point, it felt like `atomWithHash` is like a simple use case of atomWithStorage. But, since then, it have got improved/complicated, also supporting nextjs use cases. Worth keeping.
No immediate plans to change. In the future, we might consider moving to another package, if that makes sense (which might mean adding more features.)

**Comment by dai-shi** [comment]
@notsidney Hey, this is a nice article! https://dev.to/notsidney/how-and-why-you-should-store-react-ui-state-in-the-url-34pi

**Comment by notsidney** [comment]
@dai-shi Thanks! This actually reminded me, now that replaceState is documented, I can update the links in this article :)

**Pull request merged**
