### PR TITLE
Add rest examples

### PR DESCRIPTION
**Pull request by LuckyPigeon**
refer to #86 
@dai-shi 

## Add rest examples

* Hack News
* Todos
* Todos with atomFamily and localStorage
* Clock with Next.js

## Work on local

- [x] Hack News
- [x] Todos
- [x] Todos with atomFamily and localStorage
- [x] Clock with Next.js

## Work on codesandbox

- [x] [Hack News](https://githubbox.com/LuckyPigeon/jotai/tree/add_rest_examples/examples/hacker_news)
- [x] [Todos](https://githubbox.com/LuckyPigeon/jotai/tree/add_rest_examples/examples/todos)
- [x] [Todos with atomFamily and localStorage](https://githubbox.com/LuckyPigeon/jotai/tree/add_rest_examples/examples/todos_with_atomFamily_and_localStorage)
- [ ] [Clock with Next.js](https://githubbox.com/LuckyPigeon/jotai/tree/add_rest_examples/examples/clock_with_nextjs)

## Issue

* `Clock with Next.js` example at `codesandbox` could not find `tsconfig.json` in the root folder
* Suggest using this `codesandbox` link https://codesandbox.io/s/nextjs-with-jotai-forked-h4eul for now being `Clock with Next.js` example in `codesandbox`

## Error Log

* error TS5058: The specified path does not exist: '/tsconfig.json'

### CODE REVIEW

**Comment by dai-shi** [comment]
Are you still working on it? If it takes time for the clock example, we could merge the first three in advance.

**Comment by LuckyPigeon** [comment]
@dai-shi 
Merge the first three example is a good idea. I will remove clock with nextjs from commits.

**Comment by LuckyPigeon** [comment]
@dai-shi 
I have removed `clock with nextjs` example. Please check out. Thanks!

**Comment by dai-shi** [comment]
`examples/todos_with_atomFamily_and_localStorage` seems too long. how about just `examples/todos_with_atomFamily` or `examples/todos_atomFamily` ?

**Comment by LuckyPigeon** [comment]
@dai-shi 
Done. I prefer `todos_with_atomFamily`.

**Comment by dai-shi** [comment]
I didn't try everything, but it looks good. We can continue improving it. Merging this.

**Pull request merged**
