### PR TITLE
fix: esm build with new use-context-selector

### LINKED ISSUE #136: Problem with ESM/CJS configuration and Rollup
Seems your config is sending mixed messages about your package state to Rollup. I don't claim to understand the issue, but the problem arises when using [Snowpack](https://www.snowpack.dev/). @FredKSchott describes here: https://github.com/pikapkg/snowpack/discussions/1321

### PR DESCRIPTION
**Pull request by dai-shi**
close #136

### CODE REVIEW

**Comment by dai-shi** [comment]
@DynamicArray 
Could you try if this fixes your use case?
You can install the package built by codesandbox ci: https://ci.codesandbox.io/status/pmndrs/jotai/pr/138/builds/63576

**Comment by DynamicArray** [comment]
Works a treat! Thank you for fixing that so quickly.

**Comment by FredKSchott** [comment]
LGTM! Didn't run myself but checked the new use-context-selector and it looks good. Thanks for the quick fix!

**Comment by dai-shi** [comment]
Thanks both for confirmation! Merging this.

**Pull request merged**
