### PR TITLE
Benchmark tool

### PR DESCRIPTION
**Pull request by dai-shi**
Partly for #245

### CODE REVIEW

**Comment by dai-shi** [comment]
`simple-read.ts` is to show how to use the tool.

```bash
npx ts-node ./benchmarks/simple-read.ts
...
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/simple-read-*.json
"atoms=100",6528284
"atoms=1000",5508216
"atoms=10000",6301191
"atoms=100000",4776814
"atoms=1000000",4539427
```

image

**Comment by dai-shi** [comment]
```bash
npx ts-node ./benchmarks/simple-write.ts
...
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/simple-write-*.json
"atoms=100",1178969
"atoms=1000",1050401
"atoms=10000",1107396
"atoms=100000",1002460
"atoms=1000000",947639
```

image

**Review by Aslemammad — COMMENTED** [review]
Looks good to me, a good inspiration; I'm getting react-redux-benchmarks done.

**Comment by dai-shi** [comment]
```bash
npx ts-node ./benchmarks/subscribe-write.ts
...
jq -r '[.results[0].name,.results[0].ops]|@csv' benchmarks/subscribe-write-*.json
"atoms=100",379557
"atoms=1000",357439
"atoms=10000",374887
"atoms=100000",357717
"atoms=1000000",227648
```
image

**Comment by dai-shi** [comment]
Let's merge this and we can continue adding more complex scenarios later on.

**Comment by dai-shi** [comment]
I made a chart for linear axis instead of logarithmic axis.
This is out of `subscribe-write` and I stopped the node process each time.

image

The result is not very nice. I see it drops roughly linearly.

**Comment by dai-shi** [comment]
Trying with smaller size of atoms.

image

Hm, it looks about constant.

**Comment by dai-shi** [comment]
image

A little drop?

So much for now.

**Pull request merged**
