### PR TITLE
fix: declare @types/react as peerDep to avoid phantom dep

### LINKED ISSUE #2047: Declare `@types/react` as peerDeps to avoid phantom dep
## Summary

`jotai` imports `@types/react` but doesn't declare it in `package.json`, so in some monorepos there will be a 'phantom dep' problem that caused by two `@types/react` which has different major.

## Link to reproduction

https://github.com/wjw99830/phantom-dep

### Steps
- run `pnpm i`
- run `cd packages/react-18 && pnpm remove @types/react && pnpm i @types/react@18`, **in order to hoist `@types/react@18` to `.pnpm/node_modules`**
- restart ts server, then look at the definition of `JSX.Element` in `packages/react-17/src/index.tsx`. There are two definitions.

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

### PR DESCRIPTION
**Pull request by wjw99830**
## Related Issues or Discussions

Fixes #2047 

## Check List

- [ ] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Review by dai-shi — APPROVED** [review]
Oh, you already opened a PR. Thanks!

Can you do the same for https://github.com/pmndrs/zustand and https://github.com/pmndrs/valtio ?

**Comment by wjw99830** [comment]
Could you publish a prerelease version?
Let me test it for correctness in my case.

**Comment by dai-shi** [comment]
You can use codesandbox build.

https://ci.codesandbox.io/status/pmndrs/jotai/pr/2048
☝️ Find "Local Install Instructions"

**Comment by wjw99830** [comment]
> 

Thanks!

**Comment by wjw99830** [comment]
Ah, it works. Could you release a version plz? I need to upgrade the version of `jotai` in my private project to solve the problem.

**Comment by dai-shi** [comment]
I'll release it with other changes later. You can feel free to use the codesandbox build meanwhile.
I'm also waiting for PRs for zustand and valtio. Please let me know if you are not willing to work on them.

**Comment by wjw99830** [comment]
OK. I'm willing to do the same things on them later.

**Pull request merged**
