### PR TITLE
create csj bundle for utils

### LINKED ISSUE #61: [Next.js] Error using useUpdateAtom
Using Next.js
Attached screenshot
The code is like this
```ts
import { atom, useAtom } from 'jotai'
import { useUpdateAtom } from 'jotai/utils'

const eventsAtom = atom<Events>([])

export const useCreateSSE = () => {
    let updateEvents = useUpdateAtom(eventsAtom)
}
```

Wrapping Component in _app with Provider
And then using this custom hook in some component

When I used useUpdateAtom code directly, just copied from the repo, it worked.

my tsconfig:
```json
{
    "compilerOptions": {
        "target": "es6",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "downlevelIteration": true,
        "baseUrl": ".",
        "allowSyntheticDefaultImports": true,
        "jsx": "preserve",
        "paths": {
            "~/*": ["./src/*"]
        }
    },
    "exclude": ["node_modules", "public", "not_used"],
    "include": ["next-env.d.ts", "src/**/*.ts", "src/**/*.tsx", "src/**/*.jsx", "src/**/*.js"]
}
```

image

### LINKED ISSUE #63: No .cjs version of utils avaliable
There’s a `index.cjs` file in the distribution, but no `utils.cjs`, is there any reason? I’m trying to debug an error with jest so I’m just wondering. Thanks!

### PR DESCRIPTION
**Pull request by dai-shi**
Close #61. Close #63. 

```js
import { useUpdateAtom } from 'jotai/utils.cjs.js'
```

### CODE REVIEW

**Comment by dai-shi** [comment]
@lishine Could you try with this? See the codesandbox bot message.

**Comment by lishine** [comment]
I actually don't know how to test it
The codesandbox link goes to homepage

**Comment by dai-shi** [comment]
https://ci.codesandbox.io/status/pmndrs/jotai/pr/62/builds/56354
has "Local install instructions."
Basically, you replace "0.7.0" with "https://pkg.csb.dev/pmndrs/jotai/commit/002bfd19/jotai"

**Comment by lishine** [comment]
Done
It works

**Pull request merged**
