### PR TITLE
docs: migrate Codesandbox embed for next.js swc example to Stackblitz

### PR DESCRIPTION
**Pull request by niklasbec**
## Summary

- Moves the code examples from Codesandbox to Stackblitz .
https://stackblitz.com/orgs/custom/Jotai/projects (Team access needed to view the whole collection).
- Added disclaimer to Persistence 1 Example because I wasn't sure add first what I had to do and other users might be confused as well.
- Same disclaimer for the second example.
- Jotai example atomWithBroadcast had a bug in the broadcast mount function which broke the example (fixed it).

## Issues in code examples

- For trpc the example is broken because the pokemon api is offline, do we know the dev who built it do you have a replacement api in mind I can use so we don't run into the same issue again?
- The swc example doesn't work because Stackblitz struggles with swc's, if you clone the Stackblitz it works @dai-shi suggested adding a disclaimer.
- Didn't manage to get Relay working => https://stackblitz.com/edit/vitejs-vite-divyhe
- I didn't move the Babel and Parcel example to StackBlitz, I have no clue about either and how they intergrate with StackBlitz.

## Check List

- [x] `pnpm run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dai-shi** [comment]
Hi, thanks for working on this.
Are you able to run codesandbox one? I just tried and I can't.

https://stackblitz.com/edit/stackblitz-starters-ha5txx?file=app%2Fpage.tsx

Running it, it shows `undefined: 1` in the console log. Can you confirm?
image

I think it should show `countAtom: 1`. Maybe we need to update packages?

**Comment by niklasbec** [comment]
> Hi, thanks for working on this. Are you able to run codesandbox one? I just tried and I can't.
> 
> https://stackblitz.com/edit/stackblitz-starters-ha5txx?file=app%2Fpage.tsx
> 
> Running it, it shows `undefined: 1` in the console log. Can you confirm? image
> 
> I think it should show `countAtom: 1`. Maybe we need to update packages?

I will see if I can fix this.

**Comment by niklasbec** [comment]
@dai-shi there used to be a problems with swcs on earlier next versions, but pulling that up doesn't fix it. I cloned the stackblitz and ran it locally without issues so I am relatively confident this is an issue with stackblitz handling swcs.

I will see if I can do anything about it later, and will replace the code examples running on codesandbox that don't use swcs.

**Comment by dai-shi** [comment]
> I cloned the stackblitz and ran it locally without issues

That's at least good to know.

If you don't find a solution, we can probably merge this if you add a note somewhere saying it has to be downloaded to use.

**Comment by niklasbec** [comment]
> > I cloned the stackblitz and ran it locally without issues
> 
> That's at least good to know.
> 
> If you don't find a solution, we can probably merge this if you add a note somewhere saying it has to be downloaded to use.

Please see my updated comment :)

**Review by dai-shi — APPROVED** [review]
wow, this great. let's merge it and see how it goes.

**Comment by dai-shi** [comment]
Thanks for your contribution! Feel free to improve docs more.

**Comment by niklasbec** [comment]
Right now it is not showing the preview by default but only the code and you have to do a click to see the build preview. I will make a PR for that tomorrow.

**Pull request merged**
