### PR TITLE
feat(build): set some files to the client only for React Server Components use case

### PR DESCRIPTION
**Pull request by himself65**
## Related Issues or Discussions

Discussion: https://github.com/pmndrs/jotai/discussions/2241#discussioncomment-7504062

## Summary

```ts
import 'jotai/react'
import 'jotai/utils'
```

Are not allowed in the server component since it import `useEffect` and `useState.` directly or indirectly

You can import `jotai/vanilla`

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by himself65** [comment]
I think there is another approach that could make `import 'jotai'` work on the server side is to set `react-server` field in package.json.

You can see https://github.com/vercel/swr/blob/41b061306e2ce8b64e2923b1594e8db525c9368a/package.json#L36 for example

**Comment by dai-shi** [comment]
Please add the directive only in `jotai/react` and `jotai/react/utils`. That's enough.

I don't think `react-server` condition helps it, though it would improve the DX in addition.

**Review by dai-shi — CHANGES_REQUESTED** [review]
> Please add the directive only in jotai/react and jotai/react/utils.

**Comment by himself65** [comment]
Sorry for the late response. I will update the PR today

**Comment by himself65** [comment]
btw, yarn now has 4.x version. Have any plans to migrate to the latest or use pnpm? I think yarn 1 is too old.

**Comment by dai-shi** [comment]
I would personally like to move to pnpm for all zustand/jotai/valtio.

**Review by dai-shi — APPROVED** [review]
The diff looks good. I'll test it locally later.

**Comment by dai-shi** [comment]
```diff
diff -r dist.orig/esm/react/utils.mjs dist/esm/react/utils.mjs
0a1
> 'use client';
diff -r dist.orig/esm/react.mjs dist/esm/react.mjs
0a1
> 'use client';
diff -r dist.orig/package.json dist/package.json
88c88
<     "react": {
---
>     "@types/react": {
91c91
<     "@types/react": {
---
>     "react": {
94c94,95
<   }
---
>   },
>   "packageManager": "yarn@1.22.1"
diff -r dist.orig/react/utils.js dist/react/utils.js
0a1
> 'use client';
diff -r dist.orig/react.js dist/react.js
0a1
> 'use client';
diff -r dist.orig/system/react/utils.development.js dist/system/react/utils.development.js
0a1
> 'use client';
diff -r dist.orig/system/react/utils.production.js dist/system/react/utils.production.js
0a1
> 'use client';
diff -r dist.orig/system/react.development.js dist/system/react.development.js
0a1
> 'use client';
diff -r dist.orig/system/react.production.js dist/system/react.production.js
0a1
> 'use client';
diff -r dist.orig/umd/react/utils.development.js dist/umd/react/utils.development.js
0a1
> 'use client';
diff -r dist.orig/umd/react.development.js dist/umd/react.development.js
0a1
> 'use client';
```
I'm not sure if we need to modify UMD/SystemJS, but it may not hurt.

**Comment by L-Qun** [comment]
I just want to understand the reason for adding 'use client' to all files associated with React. From my understanding, it actually only needs to be added to files containing a `Provider`, since the 'use client' directive acts as a client boundary for components, right? Although it won't break anything. I look forward to your reply, thanks. @dai-shi

**Comment by dai-shi** [comment]
> it actually only needs to be added to files containing a Provider

Yes, usage-wise I think so too.

> it won't break anything.

And, that's why. I'm not sure if there's any drawback, like error message.

**Pull request merged**
