### PR TITLE
feat: jotai/rxjs

### PR DESCRIPTION
**Pull request by dai-shi**
from: https://github.com/pmndrs/jotai/issues/234#issuecomment-791841901

- [x] read-only atomWithObservable
- [x] writable atomWithObservable
- [x] tests
- examples (help wanted)
- docs (help wanted)

### CODE REVIEW

**Comment by dai-shi** [comment]
https://codesandbox.io/s/react-typescript-forked-f5hw7?file=/src/App.tsx
Here's the minimal example.

@nibtime Can you experiment with this?

**Comment by nibtime** [comment]
@dai-shi wow that went fast! Sure, if there's already a setup I prefer that.

what's your preferred way of feedback once I got something going?

**Comment by dai-shi** [comment]
@nibtime Would you join pmndrs discord server and also DM me? https://discord.gg/poimandres

**Comment by dai-shi** [comment]
Would anyone else be interested in working on this?

**Comment by dai-shi** [comment]
@Thisen If you can work on it, please assign yourself. Or, should we create an issue for this and assign? I'm actually OK to close this.

**Comment by Thisen** [comment]
@dai-shi I've assigned myself.

**Comment by dai-shi** [comment]
This need to be re-implemented.

**Comment by dai-shi** [comment]
I feel like we should ship this as an experimental feature and look for contributors.

**Pull request merged**
