### PR TITLE
breaking(core): avoid continuable promise in store api

### PR DESCRIPTION
**Pull request by dai-shi**
fix #2682

This introduces a behavioral breaking change in the promise behavior with Store API.

### CODE REVIEW

**Comment by dai-shi** [comment]
Hm, this requires `AbortController` always, whereas previously it's only used when `{ signal }` is used.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/discussions/2682#discussioncomment-10451718
Waiting for @martinhath response.

**Comment by martinhath** [comment]
I’m unable to work on this for the next two weeks, but will happily continue after that @dai-shi 😄

**Comment by dai-shi** [comment]
@martinhath I made a small change, which may not relate to your issue, but just in case.

**Comment by dmaskasky** [comment]
> fix #2682
> 
> This introduces a behavioral breaking change in the promise behavior with Store API.

What is the change in behavior?

**Comment by dai-shi** [comment]
> What is the change in behavior?

Previously, `store.get(atom)` returns a "continuable" promise, but with this PR it's not the case. So, the change is required for #2682. See some tests are changed, some of which might have been added by you.

**Comment by martinhath** [comment]
I've been testing it again, and can't reproduce the error I got last time 🤔

**Comment by dai-shi** [comment]
Thanks for confirming. I think ba0a731 improved it.

**Pull request merged**
